service: serverless-slack-invite-api

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  timeout: 30
  environment:

# NOTE: update these with our slack domain and token
    slack_domain: YOUR_SLACK_SUBDOMAIN.slack.com
    slack_token: YOUR_SLACK_TOKEN

functions:
  invite:
    handler: handler.invite
    events:
      - http:
          path: invite
          method: post
          cors: true
